name: Meal Identification
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./0_meal_identification/meal_identification

    steps:
    - uses: actions/checkout@v4

#    - name: Cache conda env
#      uses: actions/cache@v3
#      with:
#        path: /usr/share/miniconda/envs/meal_identification_ci
#        key: conda-${{ runner.os }}-${{ hashFiles('./0_meal_identification/meal_identification/environment-ci.yml') }}

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: meal_identification_ci
        environment-file: ./0_meal_identification/meal_identification/environment-ci.yml
        python-version: '3.12'
        auto-activate-base: false
        conda-solver: classic

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest -v --color=yes

    - name: Package Installation Test
      shell: bash -l {0}
      run: |
        pip install -e .